
export const MOVIE_ACTION_TYPES = {
    SET_CURRENT_MOVIE: 'SET_CURRENT_MOVIE',
    SET_MOVIES_ARRAY: 'SET_MOVIES_ARRAY',
    SET_IS_SEARCHING: 'SET_IS_SEARCHING',
    SET_IS_ADDING_MOVIE: 'SET_IS_ADDING_MOVIE',
    SET_SEARCH_STRING: 'SET_SEARCH_STRING'
}