export const QUERY_ACTION_TYPES = {
    SET_SEARCH_STRING : 'SET_SEARCH_STRING',
    SET_LIMIT: 'SET_LIMIT',
    SET_OFFSET: 'SET_OFFSET',
    SET_SORT_BY: 'SET_SORT_BY',
    SET_SORT_ORDER: 'SET_SORT_ORDER',
    SET_SEARCH_BY: 'SET_SEARCH_BY',
    SET_FILTER: 'SET_FILTER'
}